#!/usr/bin/env python
# -*- coding:utf-8 -*-

from multiprocessing import cpu_count

from input_data.scripts.configuration import ARXMLIV_NOPROBLEM_JSON_OPT_FILENAME, ARXMLIV_NOPROBLEM_JSON_SLT_FILENAME, ARXMLIV_NOPROBLEM_JSON_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_JSON_INFIX_FILENAME, ARXMLIV_NOPROBLEM_JSON_LATEX_FILENAME, ARXMLIV_NOPROBLEM_HTML5_NUM_PARAGRAPHS, POOL_CHUNKSIZE, POOL_NUM_WORKERS, ARQMATH_COLLECTION_POSTS_NUM_DOCUMENTS, ARQMATH_COLLECTION_POSTS_OPT_FILENAME, ARQMATH_COLLECTION_POSTS_SLT_FILENAME, ARQMATH_COLLECTION_POSTS_PREFIX_FILENAME, ARQMATH_COLLECTION_POSTS_INFIX_FILENAME, ARQMATH_COLLECTION_POSTS_LATEX_FILENAME


def parameters_to_string(parameters):
    return '_'.join(
        '='.join((str(key).replace('_', '-'), str(value)))
        for key, value in sorted(parameters.items())
    )

DATASET_PARAMETERS = {
    'phrases': 0,
}
DATASET_PARAMETER_STRING = parameters_to_string(DATASET_PARAMETERS)

FASTTEXT_PARAMETERS = {
    'sg': 1,
    'min_count': 5,
    'size': 300,
    'alpha': 0.05,
    'window': 5,
    'sample': 10**-4,
    'workers': cpu_count(),
    'min_alpha': 0,
    'negative': 5,
    'iter': 5,
    'min_n': 3,
    'max_n': 6,
    'bucket': 2 * 10**6,
}
FASTTEXT_PARAMETER_STRING = '_'.join((
    DATASET_PARAMETER_STRING,
    parameters_to_string(FASTTEXT_PARAMETERS),
))
 
TERMSIM_MATRIX_PARAMETERS = {
    'symmetric': True,
    'dominant': True,
    'nonzero_limit': 100,
}

TERMSIM_INDEX_PARAMETERS = {
    'threshold': -1.0,
    'exponent': 4.0,
}

SCM_PARAMETER_STRING = '_'.join((
    FASTTEXT_PARAMETER_STRING,
    parameters_to_string(TERMSIM_MATRIX_PARAMETERS),
    parameters_to_string(TERMSIM_INDEX_PARAMETERS),
))

INPUT_DATA_DIRNAME = 'input_data'
OUTPUT_DATA_DIRNAME = 'output_data'

ARXMLIV_OUTPUT_DIRNAME = '{}/arxiv-dataset-arXMLiv-08-2019'.format(OUTPUT_DATA_DIRNAME)
ARXMLIV_OUTPUT_FILENAME = '{}/{{}}_{{}}'.format(ARXMLIV_OUTPUT_DIRNAME)

ARQMATH_COLLECTION_POSTS_OPT_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARQMATH_COLLECTION_POSTS_OPT_FILENAME)
ARQMATH_COLLECTION_POSTS_SLT_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARQMATH_COLLECTION_POSTS_SLT_FILENAME)
ARQMATH_COLLECTION_POSTS_PREFIX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARQMATH_COLLECTION_POSTS_PREFIX_FILENAME)
ARQMATH_COLLECTION_POSTS_INFIX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARQMATH_COLLECTION_POSTS_INFIX_FILENAME)
ARQMATH_COLLECTION_POSTS_LATEX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARQMATH_COLLECTION_POSTS_LATEX_FILENAME)

ARXMLIV_NOPROBLEM_JSON_OPT_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARXMLIV_NOPROBLEM_JSON_OPT_FILENAME)
ARXMLIV_NOPROBLEM_JSON_SLT_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARXMLIV_NOPROBLEM_JSON_SLT_FILENAME)
ARXMLIV_NOPROBLEM_JSON_PREFIX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARXMLIV_NOPROBLEM_JSON_PREFIX_FILENAME)
ARXMLIV_NOPROBLEM_JSON_INFIX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARXMLIV_NOPROBLEM_JSON_INFIX_FILENAME)
ARXMLIV_NOPROBLEM_JSON_LATEX_FILENAME = '{}/{}'.format(INPUT_DATA_DIRNAME, ARXMLIV_NOPROBLEM_JSON_LATEX_FILENAME)

ARXMLIV_NOPROBLEM_FASTTEXT_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', FASTTEXT_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_FASTTEXT_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', FASTTEXT_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_FASTTEXT_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', FASTTEXT_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_FASTTEXT_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', FASTTEXT_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_FASTTEXT_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', FASTTEXT_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_FASTTEXT_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', FASTTEXT_PARAMETER_STRING)

ARXMLIV_NOPROBLEM_SCM_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', SCM_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_SCM_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', SCM_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_SCM_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', SCM_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_SCM_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', SCM_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_SCM_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', SCM_PARAMETER_STRING)
ARXMLIV_NOPROBLEM_SCM_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', SCM_PARAMETER_STRING)

ARXMLIV_NOPROBLEM_DICTIONARY_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', DATASET_PARAMETER_STRING + '.dictionary')
ARXMLIV_NOPROBLEM_DICTIONARY_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', DATASET_PARAMETER_STRING + '.dictionary')
ARXMLIV_NOPROBLEM_DICTIONARY_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', DATASET_PARAMETER_STRING + '.dictionary')
ARXMLIV_NOPROBLEM_DICTIONARY_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', DATASET_PARAMETER_STRING + '.dictionary')
ARXMLIV_NOPROBLEM_DICTIONARY_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', DATASET_PARAMETER_STRING + '.dictionary')
ARXMLIV_NOPROBLEM_DICTIONARY_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', DATASET_PARAMETER_STRING + '.dictionary')

ARXMLIV_NOPROBLEM_TFIDF_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', DATASET_PARAMETER_STRING + '.tfidf')
ARXMLIV_NOPROBLEM_TFIDF_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', DATASET_PARAMETER_STRING + '.tfidf')
ARXMLIV_NOPROBLEM_TFIDF_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', DATASET_PARAMETER_STRING + '.tfidf')
ARXMLIV_NOPROBLEM_TFIDF_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', DATASET_PARAMETER_STRING + '.tfidf')
ARXMLIV_NOPROBLEM_TFIDF_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', DATASET_PARAMETER_STRING + '.tfidf')
ARXMLIV_NOPROBLEM_TFIDF_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', DATASET_PARAMETER_STRING + '.tfidf')

ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', SCM_PARAMETER_STRING + '.json')
ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', SCM_PARAMETER_STRING + '.json')
ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', SCM_PARAMETER_STRING + '.json')
ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', SCM_PARAMETER_STRING + '.json')
ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', SCM_PARAMETER_STRING + '.json')
ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', SCM_PARAMETER_STRING + '.json')

ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_OPT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('opt', SCM_PARAMETER_STRING + '.tsv')
ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_SLT_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('slt', SCM_PARAMETER_STRING + '.tsv')
ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_PREFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('prefix', SCM_PARAMETER_STRING + '.tsv')
ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_INFIX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('infix', SCM_PARAMETER_STRING + '.tsv')
ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_LATEX_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('latex', SCM_PARAMETER_STRING + '.tsv')
ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_NOMATH_FILENAME = ARXMLIV_OUTPUT_FILENAME.format('nomath', SCM_PARAMETER_STRING + '.tsv')

ARXMLIV_NOPROBLEM_FILENAMES = [
  (ARXMLIV_NOPROBLEM_JSON_OPT_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_OPT_FILENAME, ARXMLIV_NOPROBLEM_SCM_OPT_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_OPT_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_OPT_FILENAME, ARQMATH_COLLECTION_POSTS_OPT_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_OPT_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_OPT_FILENAME, False),
  (ARXMLIV_NOPROBLEM_JSON_SLT_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_SLT_FILENAME, ARXMLIV_NOPROBLEM_SCM_SLT_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_SLT_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_SLT_FILENAME, ARQMATH_COLLECTION_POSTS_SLT_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_SLT_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_SLT_FILENAME, False),
  (ARXMLIV_NOPROBLEM_JSON_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_SCM_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_PREFIX_FILENAME, ARQMATH_COLLECTION_POSTS_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_PREFIX_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_PREFIX_FILENAME, False),
  (ARXMLIV_NOPROBLEM_JSON_INFIX_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_INFIX_FILENAME, ARXMLIV_NOPROBLEM_SCM_INFIX_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_INFIX_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_INFIX_FILENAME, ARQMATH_COLLECTION_POSTS_INFIX_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_INFIX_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_INFIX_FILENAME, False),
  (ARXMLIV_NOPROBLEM_JSON_LATEX_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_LATEX_FILENAME, ARXMLIV_NOPROBLEM_SCM_LATEX_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_LATEX_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_LATEX_FILENAME, ARQMATH_COLLECTION_POSTS_LATEX_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_LATEX_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_LATEX_FILENAME, False),
  (ARXMLIV_NOPROBLEM_JSON_LATEX_FILENAME, ARXMLIV_NOPROBLEM_FASTTEXT_NOMATH_FILENAME, ARXMLIV_NOPROBLEM_SCM_NOMATH_FILENAME, ARXMLIV_NOPROBLEM_DICTIONARY_NOMATH_FILENAME, ARXMLIV_NOPROBLEM_TFIDF_NOMATH_FILENAME, ARQMATH_COLLECTION_POSTS_LATEX_FILENAME, ARXMLIV_NOPROBLEM_TRAIN_RESULT_JSON_NOMATH_FILENAME, ARXMLIV_NOPROBLEM_VALIDATION_RESULT_TSV_NOMATH_FILENAME, True),
]
